import json
import os
from pathlib import Path

from config import (
    BASHRC_PATH,
    HELPERS_PATH,
    JSON_PATH,
    TKM_REFRESH_PATH,
    ZSHRC_PATH,
)

BASHRC_START = "# >>> termux-key-manager history >>>"
BASHRC_END = "# <<< termux-key-manager history <<<"


def trim_pytest_output(text):
    lines = text.splitlines(keepends=True)

    for index in range(len(lines) - 1, -1, -1):
        stripped = lines[index].strip()

        if stripped.endswith("[100%]"):
            progress = stripped[: -len("[100%]")].rstrip()

            if progress and all(char in ".FEsxXfPp-" for char in progress):
                return "".join(lines[index:])

    return text


def get_shell_commands():

    with open(JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    commands = []

    def collect(definition):

        if not isinstance(definition, dict):
            return

        shell = definition.get("shell")

        if shell:
            commands.append(shell)

        actions = definition.get("actions")

        if isinstance(actions, list):
            for action in actions:
                if isinstance(action, dict):
                    shell = action.get("shell")

                    if shell:
                        commands.append(shell)

        popup = definition.get("popup")

        if isinstance(popup, dict):
            collect(popup)

    for definition in data.get("definitions", {}).values():
        collect(definition)

    return list(dict.fromkeys(commands))


def update_bashrc(shell_commands):

    histignore = ":".join(
        "cpy*" if command == "cpy" else command for command in shell_commands
    )

    block = f"""{BASHRC_START}
# Auto-generated by ~/projects/termux-key-manager/update.py
# Do not edit this section manually.

export HISTIGNORE='{histignore}'

if [ -f "$HOME/.termux/helpers.sh" ]; then
    . "$HOME/.termux/helpers.sh"
fi

{BASHRC_END}"""

    if os.path.exists(BASHRC_PATH):
        with open(BASHRC_PATH, "r", encoding="utf-8") as f:
            bashrc = f.read()

    else:
        bashrc = ""

    start = bashrc.find(BASHRC_START)
    end = bashrc.find(BASHRC_END)

    if start != -1 and end != -1:
        end += len(BASHRC_END)

        bashrc = bashrc[:start] + block + bashrc[end:]

    else:
        if bashrc and not bashrc.endswith("\n"):
            bashrc += "\n"

        bashrc += "\n" + block + "\n"

    with open(BASHRC_PATH, "w", encoding="utf-8") as f:
        f.write(bashrc)


def generate_helpers():

    shell_commands = get_shell_commands()

    histignore = ":".join(
        "cpy*" if command == "cpy" else command for command in shell_commands
    )

    template = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "_templates",
        "helpers.sh.template",
    )
    helpers = Path(template).read_text(encoding="utf-8").replace(
        "__TKM_HISTIGNORE__",
        histignore,
    )

    with open(HELPERS_PATH, "w", encoding="utf-8") as f:
        f.write(helpers)

    os.chmod(HELPERS_PATH, 0o700)

    refresh_template = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "_templates",
        "tkm-refresh.template",
    )

    refresh = Path(refresh_template).read_text(encoding="utf-8")

    with open(TKM_REFRESH_PATH, "w", encoding="utf-8") as f:
        f.write(refresh)

    os.chmod(TKM_REFRESH_PATH, 0o700)

    update_bashrc(shell_commands)


if __name__ == "__main__":
    generate_helpers()
