import json
import os

from config import BASHRC_PATH, HELPERS_PATH, JSON_PATH


BASHRC_START = "# >>> termux-key-manager history >>>"
BASHRC_END = "# <<< termux-key-manager history <<<"


def trim_pytest_output(text):
    lines = text.splitlines(keepends=True)

    for index in range(len(lines) - 1, -1, -1):
        stripped = lines[index].strip()

        if stripped.endswith("[100%]"):
            progress = stripped[:-len("[100%]")].rstrip()

            if progress and all(char in ".FEsxXfPp-" for char in progress):
                return "".join(lines[index:])

    return text


def get_shell_commands():

    with open(
        JSON_PATH,
        "r",
        encoding="utf-8"
    ) as f:

        data = json.load(f)

    commands = []

    for definition in data.get("definitions", {}).values():

        shell = definition.get("shell")

        if shell:
            commands.append(shell)

        popup = definition.get("popup")

        if isinstance(popup, dict):

            shell = popup.get("shell")

            if shell:
                commands.append(shell)

    return list(dict.fromkeys(commands))


def update_bashrc(shell_commands):

    histignore = ":".join(
        "cpy*" if command == "cpy" else command
        for command in shell_commands
    )

    block = f'''{BASHRC_START}
# Auto-generated by ~/projects/termux-key-manager/update.py
# Do not edit this section manually.

export HISTIGNORE='{histignore}'

if [ -f "$HOME/.termux/helpers.sh" ]; then
    . "$HOME/.termux/helpers.sh"
fi

{BASHRC_END}'''

    if os.path.exists(BASHRC_PATH):

        with open(
            BASHRC_PATH,
            "r",
            encoding="utf-8"
        ) as f:

            bashrc = f.read()

    else:

        bashrc = ""

    start = bashrc.find(BASHRC_START)
    end = bashrc.find(BASHRC_END)

    if start != -1 and end != -1:

        end += len(BASHRC_END)

        bashrc = (
            bashrc[:start]
            + block
            + bashrc[end:]
        )

    else:

        if bashrc and not bashrc.endswith("\n"):
            bashrc += "\n"

        bashrc += "\n" + block + "\n"

    with open(
        BASHRC_PATH,
        "w",
        encoding="utf-8"
    ) as f:

        f.write(bashrc)


def generate_helpers():

    shell_commands = get_shell_commands()

    histignore = ":".join(
        "cpy*" if command == "cpy" else command
        for command in shell_commands
    )

    helpers = f'''# ===========================================
# AUTO-GENERATED BY ~/projects/termux-key-manager/update.py
#
# DO NOT EDIT THIS FILE MANUALLY.
#
# Source of truth:
#     ~/projects/termux-key-manager/macros.jsonc
# ===========================================


export HISTIGNORE='{histignore}'


refresh() {{

    if python "$HOME/projects/termux-key-manager/update.py"; then

        . "$HOME/.termux/helpers.sh"

        if [ -n "$TMUX" ]; then
            tmux set-environment -g HISTIGNORE "$HISTIGNORE"
        fi

    fi
    source ~/.bashrc
}}


cpy() {{

    tmux capture-pane -p |
        sed 's/cpy$//' |
        sed ':a;/^[[:space:]]*$/{{$d;N;ba;}}' |
        termux-clipboard-set
}}




cpy_pytest() {{

    termux-clipboard-get |
        python -c 'import sys; text=sys.stdin.read(); lines=text.splitlines(keepends=True); matches=[i for i,line in enumerate(lines) if line.strip().endswith("[100%]") and line.strip()[:-6].rstrip() and all(c in ".FEsxXfPp-" for c in line.strip()[:-6].rstrip())]; start=matches[-1] if matches else None; sys.stdout.write("".join(lines[start:]) if start is not None else text)' > "$PREFIX/tmp/cpy_pytest.out"
    termux-clipboard-set < "$PREFIX/tmp/cpy_pytest.out"
    rm -f "$PREFIX/tmp/cpy_pytest.out"
}}


cpy_all() {{

    tmux capture-pane -pS - |
        sed 's/cpy_all$//' |
        sed ':a;/^[[:space:]]*$/{{$d;N;ba;}}' |
        termux-clipboard-set
}}


clr() {{

    if [ -n "$TMUX" ]; then
        tmux send-keys -t "$TMUX_PANE" C-c
        tmux send-keys -t "$TMUX_PANE" -R
        tmux clear-history
    else
        printf '\\003'
        printf '\\033c'
        clear
    fi
}}




'''

    with open(
        HELPERS_PATH,
        "w",
        encoding="utf-8"
    ) as f:

        f.write(helpers)

    os.chmod(
        HELPERS_PATH,
        0o700
    )

    update_bashrc(shell_commands)


if __name__ == "__main__":
    generate_helpers()
