import json
import os
import re

from config import HELPERS_PATH, JSON_PATH


BASHRC_PATH = os.path.expanduser("~/.bashrc")

BASHRC_START = "# >>> termux-key-manager history >>>"
BASHRC_END = "# <<< termux-key-manager history <<<"


def get_shell_commands():

    with open(
        JSON_PATH,
        "r",
        encoding="utf-8"
    ) as f:

        data = json.load(f)

    commands = []

    for definition in data.get("definitions", {}).values():

        shell = definition.get("shell")

        if shell:
            commands.append(shell)

        popup = definition.get("popup")

        if isinstance(popup, dict):

            shell = popup.get("shell")

            if shell:
                commands.append(shell)

    return list(dict.fromkeys(commands))


def update_bashrc(shell_commands):

    histignore = ":".join(shell_commands)

    block = f'''{BASHRC_START}
# Auto-generated by ~/projects/termux-key-manager/update.py
# Do not edit this section manually.

export HISTIGNORE='{histignore}'

{BASHRC_END}'''

    if os.path.exists(BASHRC_PATH):

        with open(
            BASHRC_PATH,
            "r",
            encoding="utf-8"
        ) as f:

            bashrc = f.read()

    else:

        bashrc = ""

    start = bashrc.find(BASHRC_START)
    end = bashrc.find(BASHRC_END)

    if start != -1 and end != -1:

        end += len(BASHRC_END)

        bashrc = (
            bashrc[:start]
            + block
            + bashrc[end:]
        )

    else:

        if bashrc and not bashrc.endswith("\n"):
            bashrc += "\n"

        bashrc += "\n" + block + "\n"

    with open(
        BASHRC_PATH,
        "w",
        encoding="utf-8"
    ) as f:

        f.write(bashrc)


def generate_helpers():

    shell_commands = get_shell_commands()
    histignore = ":".join(shell_commands)

    helpers = f'''# ===========================================
# AUTO-GENERATED BY ~/projects/termux-key-manager/update.py
#
# DO NOT EDIT THIS FILE MANUALLY.
#
# Source of truth:
#     ~/projects/termux-key-manager/macros.jsonc
# ===========================================


export HISTIGNORE='{histignore}'


refresh() {{

    if python "$HOME/projects/termux-key-manager/update.py"; then

        # Reload this shell immediately.
        . "$HOME/.termux/helpers.sh"

        # Update tmux server environment for future shells/panes.
        if [ -n "$TMUX" ]; then
            tmux set-environment -g HISTIGNORE "$HISTIGNORE"
        fi

    fi
}}


cpy() {{

    tmux capture-pane -p |
        sed 's/cpy$//' |
        sed ':a;/^[[:space:]]*$/{{$d;N;ba;}}' |
        termux-clipboard-set
}}


cpy_all() {{

    tmux capture-pane -pS - |
        sed 's/cpy_all$//' |
        sed ':a;/^[[:space:]]*$/{{$d;N;ba;}}' |
        termux-clipboard-set
}}


clr() {{
    if [ -n "$TMUX" ]; then
        tmux send-keys -t "$TMUX_PANE" C-c
        tmux send-keys -t "$TMUX_PANE" -R
        tmux clear-history
    else
        printf '\\003'
        printf '\\033c'
        clear
    fi
}}


'''

    with open(
        HELPERS_PATH,
        "w",
        encoding="utf-8"
    ) as f:

        f.write(helpers)

    os.chmod(
        HELPERS_PATH,
        0o700
    )

    update_bashrc(shell_commands)





