import json
import os
import re

from config import JSON_PATH, TMUX_CONF_PATH
from jsonc import strip_comments
from macros import TMUX_ACTION_COMMANDS, TMUX_ACTION_SEQUENCES

TMUX_START = "# >>> termux-key-manager tmux >>>"
TMUX_END = "# <<< termux-key-manager tmux <<<"


def get_tmux_actions():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        data = json.loads(strip_comments(f.read()))

    found = set()

    for definition in data.get("definitions", {}).values():
        for action_list in (
            definition.get("actions", []),
            (
                definition.get("popup", {}).get("actions", [])
                if isinstance(definition.get("popup"), dict)
                else []
            ),
        ):
            for action in action_list:
                if isinstance(action, dict) and "tmux" in action:
                    found.add(action["tmux"])

    return [
        action
        for action in TMUX_ACTION_SEQUENCES
        if action in found
    ]


def build_tmux_config(actions):
    if not actions:
        return ""

    lines = [
        "set -g assume-paste-time 0",
    ]

    for index, action in enumerate(actions):
        try:
            sequence = TMUX_ACTION_SEQUENCES[action]
        except KeyError:
            raise ValueError(f"unknown tmux action: {action}")

        escaped = (
            sequence.encode("unicode_escape").decode("ascii").replace(r"\x1b", r"\e")
        )
        lines.append(f'set -s user-keys[{index}] "{escaped}"')

        user_key = f"User{index}"
        command = TMUX_ACTION_COMMANDS[action]

        if command is None:
            binding = "send-keys -X cancel"
        else:
            binding = f'run-shell "{command}"'
            lines.append(f"bind-key {user_key} {binding}")

        lines.append(f"bind-key -T copy-mode {user_key} {binding}")
        lines.append(f"bind-key -T copy-mode-vi {user_key} {binding}")

    return "\n".join(lines)


def update_tmux_conf(config):
    if os.path.exists(TMUX_CONF_PATH):
        with open(TMUX_CONF_PATH, "r", encoding="utf-8") as f:
            text = f.read()
    else:
        text = ""

    block = (
        f"{TMUX_START}\n"
        "# Auto-generated by ~/projects/termux-key-manager/update.py\n"
        "# Do not edit this section manually.\n"
        "\n"
        f"{config}\n"
        f"{TMUX_END}"
    )

    pattern = re.compile(
        re.escape(TMUX_START) + r".*?" + re.escape(TMUX_END),
        re.DOTALL,
    )

    if config:
        if pattern.search(text):
            text = pattern.sub(lambda _: block, text, count=1)
        else:
            if text and not text.endswith("\n"):
                text += "\n"
            text += "\n" + block + "\n"
    else:
        text = pattern.sub("", text)
        text = text.rstrip() + ("\n" if text.strip() else "")

    with open(TMUX_CONF_PATH, "w", encoding="utf-8") as f:
        f.write(text)


def generate_tmux_config():
    actions = get_tmux_actions()
    config = build_tmux_config(actions)
    update_tmux_conf(config)


if __name__ == "__main__":
    generate_tmux_config()
