import json
import os
import re

from config import JSON_PATH, TMUX_CONF_PATH
from jsonc import strip_comments
from macros import TMUX_ACTION_SEQUENCES


TMUX_START = "# >>> termux-key-manager tmux >>>"
TMUX_END = "# <<< termux-key-manager tmux <<<"


def get_tmux_actions():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        data = json.loads(strip_comments(f.read()))

    actions = []

    for definition in data.get("definitions", {}).values():
        for action in definition.get("actions", []):
            if isinstance(action, dict) and "tmux" in action:
                actions.append(action["tmux"])

        popup = definition.get("popup")
        if isinstance(popup, dict):
            for action in popup.get("actions", []):
                if isinstance(action, dict) and "tmux" in action:
                    actions.append(action["tmux"])

    return list(dict.fromkeys(actions))


def build_tmux_config(actions):
    if not actions:
        return ""

    lines = [
        "set -g assume-paste-time 0",
    ]

    for index, action in enumerate(actions):
        try:
            sequence = TMUX_ACTION_SEQUENCES[action]
        except KeyError:
            raise ValueError(
                f"unknown tmux action: {action}"
            )

        escaped = (
            sequence.encode("unicode_escape")
            .decode("ascii")
            .replace(r"\x1b", r"\e")
        )
        lines.append(
            f'set -s user-keys[{index}] "{escaped}"'
        )

        user_key = f"User{index}"
        lines.append(
            f"bind-key -T copy-mode {user_key} send-keys -X cancel"
        )
        lines.append(
            f"bind-key -T copy-mode-vi {user_key} send-keys -X cancel"
        )

    return "\n".join(lines)


def update_tmux_conf(config):
    if os.path.exists(TMUX_CONF_PATH):
        with open(TMUX_CONF_PATH, "r", encoding="utf-8") as f:
            text = f.read()
    else:
        text = ""

    block = (
        f"{TMUX_START}\n"
        "# Auto-generated by ~/projects/termux-key-manager/update.py\n"
        "# Do not edit this section manually.\n"
        "\n"
        f"{config}\n"
        f"{TMUX_END}"
    )

    pattern = re.compile(
        re.escape(TMUX_START)
        + r".*?"
        + re.escape(TMUX_END),
        re.DOTALL,
    )

    if config:
        if pattern.search(text):
            text = pattern.sub(block, text, count=1)
        else:
            if text and not text.endswith("\n"):
                text += "\n"
            text += "\n" + block + "\n"
    else:
        text = pattern.sub("", text)
        text = text.rstrip() + ("\n" if text.strip() else "")

    with open(TMUX_CONF_PATH, "w", encoding="utf-8") as f:
        f.write(text)


def generate_tmux_config():
    actions = get_tmux_actions()
    config = build_tmux_config(actions)
    update_tmux_conf(config)


if __name__ == "__main__":
    generate_tmux_config()
