import json
import os
import re

from config import JSON_PATH, TMUX_CONF_PATH
from jsonc import strip_comments
from macros import TMUX_ACTION_SEQUENCES

TMUX_START = "# >>> termux-key-manager tmux >>>"
TMUX_END = "# <<< termux-key-manager tmux <<<"


def get_tmux_actions():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        data = json.loads(strip_comments(f.read()))

    actions = []

    for definition in data.get("definitions", {}).values():
        for action_list in (
            definition.get("actions", []),
            (
                definition.get("popup", {}).get("actions", [])
                if isinstance(definition.get("popup"), dict)
                else []
            ),
        ):
            if any(
                isinstance(action, dict) and "tmux" in action for action in action_list
            ):
                actions.append(
                    tuple(
                        action.get("tmux", action.get("shell"))
                        for action in action_list
                        if isinstance(action, dict)
                        and ("tmux" in action or "shell" in action)
                    )
                )

    return list(dict.fromkeys(actions))


def build_tmux_config(actions):
    if not actions:
        return ""

    lines = [
        "set -g assume-paste-time 0",
    ]

    for index, action in enumerate(actions):
        if isinstance(action, tuple):
            tmux_action = next(
                (
                    item for item in action
                    if item in TMUX_ACTION_SEQUENCES
                ),
                None,
            )
            if tmux_action is None:
                raise ValueError("mixed action has no tmux action")

            sequence = TMUX_ACTION_SEQUENCES[tmux_action]
            binding_actions = action
        else:
            try:
                sequence = TMUX_ACTION_SEQUENCES[action]
            except KeyError:
                raise ValueError(f"unknown tmux action: {action}")
            binding_actions = (action,)

        escaped = (
            sequence.encode("unicode_escape").decode("ascii").replace(r"\x1b", r"\e")
        )
        lines.append(f'set -s user-keys[{index}] "{escaped}"')

        user_key = f"User{index}"
        binding_parts = []

        for item in binding_actions:
            if item in TMUX_ACTION_SEQUENCES:
                binding_parts.append("send-keys -X cancel")
            else:
                binding_parts.append(f'run-shell "{item}"')

        binding = " \\; ".join(binding_parts)

        lines.append(f"bind-key -T copy-mode {user_key} {binding}")
        lines.append(f"bind-key -T copy-mode-vi {user_key} {binding}")

    return "\n".join(lines)


def update_tmux_conf(config):
    if os.path.exists(TMUX_CONF_PATH):
        with open(TMUX_CONF_PATH, "r", encoding="utf-8") as f:
            text = f.read()
    else:
        text = ""

    block = (
        f"{TMUX_START}\n"
        "# Auto-generated by ~/projects/termux-key-manager/update.py\n"
        "# Do not edit this section manually.\n"
        "\n"
        f"{config}\n"
        f"{TMUX_END}"
    )

    pattern = re.compile(
        re.escape(TMUX_START) + r".*?" + re.escape(TMUX_END),
        re.DOTALL,
    )

    if config:
        if pattern.search(text):
            text = pattern.sub(lambda _: block, text, count=1)
        else:
            if text and not text.endswith("\n"):
                text += "\n"
            text += "\n" + block + "\n"
    else:
        text = pattern.sub("", text)
        text = text.rstrip() + ("\n" if text.strip() else "")

    with open(TMUX_CONF_PATH, "w", encoding="utf-8") as f:
        f.write(text)


def generate_tmux_config():
    actions = get_tmux_actions()
    config = build_tmux_config(actions)
    update_tmux_conf(config)


if __name__ == "__main__":
    generate_tmux_config()
